# Generated by Django 5.2.4 on 2025-08-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_migrations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]


