# Generated by Django 5.2.8 on 2025-11-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_student_photo_remove_student_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
