# Generated by Django 5.2.4 on 2025-08-11 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='naeme',
            new_name='name',
        ),
    ]
